import type { editor } from 'monaco-editor';

export const weaveDarkTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'd8dee9', background: '08090c' },
    { token: 'keyword', foreground: 'e5a443', fontStyle: 'bold' }, // Amber keyword
    { token: 'type', foreground: '56b6c2', fontStyle: 'bold' }, // Cyan type
    { token: 'type.identifier', foreground: '4ec9b0' },
    { token: 'identifier', foreground: 'abb2bf' },
    { token: 'string', foreground: '98c379' }, // Emerald string
    { token: 'string.quote', foreground: '7fa663' },
    { token: 'string.raw', foreground: '8ab36e' },
    { token: 'string.char', foreground: 'e5c07b' },
    { token: 'string.escape', foreground: 'd19a66', fontStyle: 'bold' },
    { token: 'string.invalid', foreground: 'e06c75', fontStyle: 'underline' },
    { token: 'number', foreground: 'd19a66' }, // Gold number
    { token: 'number.float', foreground: 'e5c07b' },
    { token: 'number.hex', foreground: 'd19a66' },
    { token: 'number.octal', foreground: 'd19a66' },
    { token: 'number.binary', foreground: 'd19a66' },
    { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'comment.doc', foreground: '76839b', fontStyle: 'italic' },
    { token: 'operator', foreground: '61afef' }, // Blue/cyan operator
    { token: 'delimiter', foreground: 'abb2bf' },
    { token: 'delimiter.curly', foreground: 'ff9d00' },
    { token: 'annotation', foreground: 'c678dd', fontStyle: 'bold' }, // Purple annotation
    { token: 'constant', foreground: 'be5046', fontStyle: 'bold' },
  ],
  colors: {
    'editor.background': '#08090c',
    'editor.foreground': '#d8dee9',
    'editorCursor.foreground': '#ff9d00',
    'editor.lineHighlightBackground': '#ffffff08',
    'editorLineNumber.foreground': '#4b5263',
    'editorLineNumber.activeForeground': '#ff9d00',
    'editor.selectionBackground': '#ff9d0033',
    'editor.inactiveSelectionBackground': '#ff9d0018',
    'editorIndentGuide.background': '#ffffff0a',
    'editorIndentGuide.activeBackground': '#ffffff18',
    'editorBracketMatch.background': '#ff9d0020',
    'editorBracketMatch.border': '#ff9d00',
    'editorGutter.background': '#08090c',
    'editorWidget.background': '#0e1017',
    'editorWidget.border': '#ffffff10',
    'editorSuggestWidget.background': '#0e1017',
    'editorSuggestWidget.border': '#ffffff10',
    'editorSuggestWidget.selectedBackground': '#ff9d0028',
    'editorSuggestWidget.highlightForeground': '#ff9d00',
  },
};

export const weaveObsidianTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'e2e8f0', background: '08090c' },
    { token: 'keyword', foreground: 'ff9d00', fontStyle: 'bold' },
    { token: 'type', foreground: '06b6d4', fontStyle: 'bold' },
    { token: 'type.identifier', foreground: '22d3ee' },
    { token: 'identifier', foreground: 'cbd5e1' },
    { token: 'string', foreground: '10b981' },
    { token: 'string.quote', foreground: '059669' },
    { token: 'string.char', foreground: '34d399' },
    { token: 'string.escape', foreground: 'fbbf24' },
    { token: 'number', foreground: 'f97316' },
    { token: 'comment', foreground: '475569', fontStyle: 'italic' },
    { token: 'comment.doc', foreground: '64748b', fontStyle: 'italic' },
    { token: 'operator', foreground: '38bdf8' },
    { token: 'delimiter', foreground: '94a3b8' },
    { token: 'annotation', foreground: 'a855f7', fontStyle: 'bold' },
    { token: 'constant', foreground: 'ef4444' },
  ],
  colors: {
    'editor.background': '#08090c',
    'editor.foreground': '#e2e8f0',
    'editorCursor.foreground': '#ff9d00',
    'editor.lineHighlightBackground': '#ffffff08',
    'editorLineNumber.foreground': '#334155',
    'editorLineNumber.activeForeground': '#ff9d00',
    'editor.selectionBackground': '#ff9d0033',
    'editor.inactiveSelectionBackground': '#ff9d0018',
    'editorIndentGuide.background': '#ffffff0a',
    'editorIndentGuide.activeBackground': '#ffffff18',
    'editorGutter.background': '#08090c',
  },
};

export const weaveLightTheme: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '24292e', background: 'ffffff' },
    { token: 'keyword', foreground: 'b45309', fontStyle: 'bold' },
    { token: 'type', foreground: '0284c7', fontStyle: 'bold' },
    { token: 'type.identifier', foreground: '0369a1' },
    { token: 'identifier', foreground: '1f2937' },
    { token: 'string', foreground: '15803d' },
    { token: 'string.quote', foreground: '166534' },
    { token: 'string.char', foreground: '15803d' },
    { token: 'string.escape', foreground: 'd97706' },
    { token: 'number', foreground: 'c2410c' },
    { token: 'comment', foreground: '6b7280', fontStyle: 'italic' },
    { token: 'comment.doc', foreground: '4b5563', fontStyle: 'italic' },
    { token: 'operator', foreground: '0284c7' },
    { token: 'delimiter', foreground: '374151' },
    { token: 'annotation', foreground: '7e22ce', fontStyle: 'bold' },
    { token: 'constant', foreground: 'dc2626' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#24292e',
    'editorCursor.foreground': '#b45309',
    'editor.lineHighlightBackground': '#f3f4f6',
    'editorLineNumber.foreground': '#9ca3af',
    'editorLineNumber.activeForeground': '#b45309',
    'editor.selectionBackground': '#e0e7ff',
    'editorIndentGuide.background': '#e5e7eb',
    'editorIndentGuide.activeBackground': '#d1d5db',
    'editorGutter.background': '#ffffff',
  },
};
